### ISSUE TITLE
Modify the welcome page UI

### ISSUE THREAD

**Issue by sarcasticdhruv** [sarcasticdhruv/Fire-Notes#1]
It's beginner friendly.
Just modify the welcome page, it requires basic web dev knowledge.

**Comment by Aarshit-33** [comment]
what do you exactly wants to in the welcome page.

like any reference idea or any design up to your mind ?

@sarcasticdhruv

**Comment by sarcasticdhruv** [comment]
@Aarshit-33
I would like the following updates and features to be implemented for the platform:

Page 1: A welcoming screen with the message:

"What will you achieve today? Remember everything and tackle any project with your notes all in one place."
Page 2: A "What's New" section to showcase information about new features or updates.

Page 3: A horizontally aligned layout with 4 key bullet points:

Work anywhere
Remember everything
Turn to-do into done
Find things fast
Page 4: A security-focused section with the following message:

"Your info is secure: Use Firenotes to capture more than just words. Harness the power of the internet store your important files and documents. No matter if it’s meeting notes, receipts, manuals, or family recipes, Firenotes keeps them secure."
Include relevant supporting images for this section.
Footer: Add a footer to provide navigation and other necessary links.

Additionally, ensure the overall design is interactive and visually modern, incorporating engaging elements to enhance user experience.
